### ISSUE TITLE
Query parameters are not maintained when redirecting

### ISSUE THREAD

**Issue by timwisbauer** [fastly/compute-rust-auth#13]
The query parameters are encoded into the state cookie, but they aren't turned back into query parameters when the client is redirected after successful authentication.  As an example if a client browses to `foo.test.com/?lang=en` and is redirected for authentication they are redirected to `foo.test.com/lang=en` after authentication.  

I think this may be related to how the state is constructed.

```
    let state = format!(
        "{}{}{}",
        req.get_path(),
        req.get_query_str().unwrap_or(""),
        rand_chars(settings.config.state_parameter_length)
    );
```

Since `get_query_str()` doesn't include the `?` denoting a query string the query is combined with the URL.

I fixed this temporarily by adding `?` to the state.

```
    let state = format!(
        "{}?{}{}",
        req.get_path(),
        req.get_query_str().unwrap_or(""),
        rand_chars(settings.config.state_parameter_length)
    );
```

However, this appends `?` to every URL whether a query exists or not which works for my use case, but is not an ideal solution.

**Comment by timwisbauer** [comment]
I ended up improving on this by conditionally prepending `?` to the query string.

```
    // If a query string isn't empty, prepend ? to the state.
    let query_str = if req.get_query_str().unwrap_or("") != "" {
        format!("?{}", req.get_query_str().unwrap_or(""))
    } else {
        // Query string was empty.
        "".to_string()
    };
    let state = format!(
        "{}{}{}",
        req.get_path(),
        query_str,
        rand_chars(settings.config.state_parameter_length)
    );
```

**Comment by doramatadora** [comment]
Thank you for this fix, @timwisbauer 💟  It shipped with https://github.com/fastly/compute-rust-auth/pull/14.
