### ISSUE TITLE
How to add tests?

### ISSUE THREAD

**Issue by timsuchanek** [fastly/compute-rust-auth#8]
When I add a test via `#[cfg(test)]` and want to run it via `cargo test`, I get the following error:
```
/root/code/fastly/target/wasm32-wasi/debug/deps/fastly_template_rust_default-9e518162b40fafa3.wasm: 1: Syntax error: end of file unexpected
error: test failed, to rerun pass '--bin fastly-template-rust-default'
```
Can you add an example for how to write a simple test and how to run it?
Thanks!

**Comment by yannh** [comment]
@timsuchanek Try cargo test --target TARGET_PLATFORM  with TARGET_PLATFORM being one of https://doc.rust-lang.org/rustc/platform-support.html matching your build environment. It worked for me for the compute-rust-starter-kit. 

I agree this project could really use some tests :+1:
